name: Build and Test Angular Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.13.2

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  
  test:
    needs: build
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.13.2

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
  
  deploy: 
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.13.2

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.5.0
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          BRANCH: main
          FOLDER: dist
